version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-base
    container_name: api-base
    restart: always
    env_file: .env
    ports:
      - "80:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

    networks:
    - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  